use usbd_human_interface_device::page::Keyboard;

pub fn emoji_macro(key: Keyboard) -> Option<&'static str> {
    match key {
        Keyboard::A => Some(":regional_indicator_a: "),
        Keyboard::B => Some(":regional_indicator_b: "),
        Keyboard::C => Some(":regional_indicator_c: "),
        Keyboard::D => Some(":regional_indicator_d: "),
        Keyboard::E => Some(":regional_indicator_e: "),
        Keyboard::F => Some(":regional_indicator_f: "),
        Keyboard::G => Some(":regional_indicator_g: "),
        Keyboard::H => Some(":regional_indicator_h: "),
        Keyboard::I => Some(":regional_indicator_i: "),
        Keyboard::J => Some(":regional_indicator_j: "),
        Keyboard::K => Some(":regional_indicator_k: "),
        Keyboard::L => Some(":regional_indicator_l: "),
        Keyboard::M => Some(":regional_indicator_m: "),
        Keyboard::N => Some(":regional_indicator_n: "),
        Keyboard::O => Some(":regional_indicator_o: "),
        Keyboard::P => Some(":regional_indicator_p: "),
        Keyboard::Q => Some(":regional_indicator_q: "),
        Keyboard::R => Some(":regional_indicator_r: "),
        Keyboard::S => Some(":regional_indicator_s: "),
        Keyboard::T => Some(":regional_indicator_t: "),
        Keyboard::U => Some(":regional_indicator_u: "),
        Keyboard::V => Some(":regional_indicator_v: "),
        Keyboard::W => Some(":regional_indicator_w: "),
        Keyboard::X => Some(":regional_indicator_x: "),
        Keyboard::Y => Some(":regional_indicator_y: "),
        Keyboard::Z => Some(":regional_indicator_z: "),
        Keyboard::Keyboard1 => Some(":one: "),
        Keyboard::Keyboard2 => Some(":two: "),
        Keyboard::Keyboard3 => Some(":three: "),
        Keyboard::Keyboard4 => Some(":four: "),
        Keyboard::Keyboard5 => Some(":five: "),
        Keyboard::Keyboard6 => Some(":six: "),
        Keyboard::Keyboard7 => Some(":seven: "),
        Keyboard::Keyboard8 => Some(":eight: "),
        Keyboard::Keyboard9 => Some(":nine: "),
        Keyboard::Keyboard0 => Some(":zero: "),
        Keyboard::Space => Some(":black_large_square: "),
        Keyboard::DeleteBackspace => Some(":rewind: "),
        _ => None,
    }
}
